msv: fix missing function import
  File ".../h5mdtools/_plot/msv.py", line 168, in plot
    x = mean(reshape(x, shape), axis=1)
NameError: global name 'reshape' is not defined